version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    depends_on:
      - model_volume

  frontend:
    build:
      context: ./src/interface
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "8501:8501"
    volumes:
      - ./src/interface:/app
    depends_on:
      - backend

  model_volume:
    image: alpine
    volumes:
      - ./src/backend/model_close.h5:/model/model_close.h5
    entrypoint: ["/bin/true"]
