version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_crypto
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./interface
      dockerfile: Dockerfile
    container_name: frontend_crypto
    ports:
      - "8501:8501"
    volumes:
      - ./interface:/app
    depends_on:
      - backend
